# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docker-registry

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: private-registry-tls-secret
    type: kubernetes.io/tls
    files:
      - tls.crt=private.registry.com.crt
      - tls.key=private.registry.com.key
#test
resources:
  - registry.yaml
