apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: docker-registry
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeName: ubuntu02
      containers:
        - name: registry
          image: registry:2
          env:
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/var/lib/secrets/tls.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/var/lib/secrets/tls.key"
          - name: REGISTRY_HTTP_ADDR
            value: "0.0.0.0:443"
          - name: REGISTRY_HTTP_HOST
            value: "https://private.registry.com:443"
          - name: REGISTRY_HTTP_SECRET
            value: "mysecret"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: registry-storage
              mountPath: "/var/lib/registry"
            - name: tls-volume
              mountPath: "/var/lib/secrets"
              readOnly: true
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: tls-volume
          secret:
            secretName: private-registry-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: docker-registry
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: private.registry.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 443