apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: docker-registry
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeName: ubuntu02
      containers:
        - name: registry
          image: registry:2
          env:
          - name: REGISTRY_HTTP_SECRET
            value: "mysecret"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: "/var/lib/registry"
            - name: tls-volume
              mountPath: "/var/lib/secrets"
              readOnly: true
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: tls-volume
          secret:
            secretName: private-registry-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: docker-registry
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"           # Unlimited size
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"     # 1 hour
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off" # avoid nginx storing temp file locally during image upload
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - private.registry.com
      secretName: private-registry-tls-secret
  rules:
    - host: private.registry.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 5000