apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: llm-train
spec:
  entrypoint: train-model
  volumeClaimTemplates:
  - metadata:
      name: model-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: local-storage
      volumeName: local-pv-llm
  templates:
  - name: train-model
    container:
      image: private.registry.com:31445/lightweight-llm-trainer:latest
      command: [python]
      args: ["train_model_small.py"]
      volumeMounts:
      - name: model-pvc
        mountPath: /mnt/output
