apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: llm-train
spec:
  entrypoint: main-dag
  arguments:
    parameters:
      - name: model-name
        #value: sshleifer/tiny-gpt2
        value: distilgpt2
      - name: run-train # if false, only inference is executed.
        value: "true"  
      - name: subset-lenght-to-train # 0 for full dataset otherwise a value.
        value: "5000"
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: model-pvc
  templates:
    - name: main-dag
      dag:
        tasks:
          - name: train-and-predict-path
            template: dag-train-and-predict
            when: "{{workflow.parameters.run-train}} == true"
            arguments:
              parameters:
                - name: model-name
                  value: "{{workflow.parameters.model-name}}"
                - name: subset-lenght-to-train
                  value: "{{workflow.parameters.subset-lenght-to-train}}"

          - name: predict-only-path
            template: dag-predict-only
            when: "{{workflow.parameters.run-train}} == false"
            arguments:
              parameters:
                - name: model-name
                  value: "{{workflow.parameters.model-name}}"

    - name: dag-train-and-predict
      inputs:
        parameters:
          - name: model-name
          - name: subset-lenght-to-train
      dag:
        tasks:
          - name: train
            template: train-model
            arguments:
              parameters:
                - name: model-name
                  value: "{{inputs.parameters.model-name}}"
                - name: subset-lenght-to-train
                  value: "{{inputs.parameters.subset-lenght-to-train}}"

          - name: predict
            dependencies: [train]
            template: run-inference
            arguments:
              parameters:
                - name: model-name
                  value: "{{inputs.parameters.model-name}}"

    - name: dag-predict-only
      inputs:
        parameters:
          - name: model-name
      dag:
        tasks:
          - name: predict
            template: run-inference
            arguments:
              parameters:
                - name: model-name
                  value: "{{inputs.parameters.model-name}}"

    - name: train-model
      inputs:
        parameters:
          - name: model-name
          - name: subset-lenght-to-train
      container:
        image: private.registry.com:31445/lightweight-llm-trainer:latest
        command: ["python"]
        args: ["train_model_small.py", "{{inputs.parameters.model-name}}", "{{inputs.parameters.subset-lenght-to-train}}"]
        volumeMounts:
          - name: shared-data
            mountPath: /mnt/output
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        nodeSelector:
          kubernetes.io/hostname: "ubuntu02"

    - name: run-inference
      inputs:
        parameters:
          - name: model-name
      container:
        image: private.registry.com:31445/lightweight-llm-trainer:latest
        command: ["python"]
        args: ["predict_model_small.py", "{{inputs.parameters.model-name}}"]
        volumeMounts:
          - name: shared-data
            mountPath: /mnt/output
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        nodeSelector:
          kubernetes.io/hostname: "ubuntu02"
