apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-infer
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: infer
  template:
    metadata:
      labels:
        app: infer
    spec:
      containers:
      - name: infer
        image: private.registry.com:31445/inference-ui:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dvc-current-model
          mountPath: /mnt/output/
      volumes:
        - name: dvc-current-model
          nfs:
            path: /mnt/dvc/current
            server: 192.168.137.21
            readOnly: false
  strategy:
    blueGreen:
      activeService: fastapi-infer-service-active
      previewService: fastapi-infer-service-preview
      autoPromotionEnabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-infer-service-active
spec:
  selector:
    app: infer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-infer-service-preview
spec:
  selector:
    app: infer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infer-ui
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: inference.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-infer-service
                port:
                  number: 8000