project: default
source:
  repoURL: https://github.com/alessiofilippin/arcocdlocal.git
  path: cluster-conf
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: default