apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-llm-inference-ro
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/registry/llm
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu02