apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-dvc-repo
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/dvc/repo