apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sentiment-analysis-pipeline-1
spec:
  entrypoint: sentiment-pipeline
  templates:
    - name: sentiment-pipeline
      steps:
        - - name: train-model
            template: train-step
        - - name: evaluate-model
            template: evaluate-step

    - name: train-step
      container:
        image: my-sentiment-image
        command: ["python"]
        args: ["/train_sentiment.py"]
        volumeMounts:
          - name: model-volume
            mountPath: /tmp

    - name: evaluate-step
      container:
        image: my-sentiment-image
        command: ["python"]
        args: ["/evaluate.py"]
        volumeMounts:
          - name: model-volume
            mountPath: /tmp

  volumes:
    - name: model-volume
      emptyDir: {}
