apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: promote-model-version
  name: argo-workflow-role
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: promote-model-version
subjects:
  - kind: ServiceAccount
    name: default
    namespace: promote-model-version
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
