apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvc
  template:
    metadata:
      labels:
        app: dvc
    spec:
      containers:
        - name: dvc
          image: private.registry.com:31445/dvc:latest
          command: ["ls", "-lh", "/home/dvcuser/dvcdata"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: dvc-storage-repo
              mountPath: /home/dvcuser/dvcdata
      volumes:
        - name: dvc-storage-repo
          nfs:
            path: /mnt/dvc/repo
            server: 192.168.137.21
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: dvc-service
spec:
  selector:
    app: dvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dvc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dvc.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dvc-service
                port:
                  number: 80